services:
  pg:
    image: postgres:17
    container_name: agenda-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: agenda_pg
    networks:
      - agendapoli

  pgadmin:
    image: dpage/pgadmin4
    container_name: agenda-pgadmin
    ports: 
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - pg
    networks:
      - agendapoli

networks:
  agendapoli:
    driver: bridge
